version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: calvio-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  algorithm:
    build: ./algorithm-microservice
    container_name: calvio-algorithm
    ports:
      - "8000:8000"
    volumes:
      - ./algorithm-microservice:/app
  postgres:
    image: postgres:13
    container_name: calvio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calvio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
